version: "3.9"
services:
  web-service:
    restart: unless-stopped
    build:
      context: "./web-service"
      dockerfile: Dockerfile
    volumes:
      - "./web-service:/app/"
      - "./models:/app/models/"
    ports:
      - "5000"

  api-gateway:
    restart: always
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
